### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tesla3327** [scottjodoin/hangman-online#1]
Overall it looks really good to me. There's professionally written code that isn't as thorough as this is.

I really like that you handle edge cases and errors nicely, not everyone remembers those things. https://github.com/scottjodoin/hangman-online/blob/9094df375e90432f947157053865b2974f86bb4d/hangman-controller.js#L220-L222

It seems well designed too, with hashes for game IDs, handling all cases for when someone leaves the game, joins a game, stripping info so client can't cheat, etc.

For improvement, you could do better with splitting up large chunks of code into smaller functions, and splitting large files into smaller files too. I like functions around 40-50 lines max, but that's a personal preference.

Formatting could also be done better. Two popular ones are [Prettier](https://prettier.io/) and [ESLint](https://eslint.org/). They'll also catch small things like using `var`, `let`, and `const` consistently.

Adding tests, unit tests but also UI tests, would get you bonus points here for sure.

**Comment by scottjodoin** [comment]
Thank you for the valuable feedback!
